### PR TITLE
Deprecation

### PR DESCRIPTION
**Pull request by charlie-becker**
1. Added a `deprecated` module with the old models, losses, and callbacks. 
2. Modified `losses.py` to remove old losses and add new ones
3. Modified `callbacks.py` to remove old ones and add new ones

### CODE REVIEW

**Comment by djgagne** [comment]
The CI had the following error

```bash
ImportError while importing test module '/home/runner/work/miles-guess/miles-guess/mlguess/tests/test_models.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../../micromamba/envs/guess/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
mlguess/tests/test_models.py:9: in <module>
    from mlguess.keras.models import BaseRegressor as RegressorDNN
mlguess/keras/models.py:13: in <module>
    from mlguess.keras.losses import EvidentialRegressionLoss, EvidentialRegressionCoupledLoss, gaussian_nll
E   ImportError: cannot import name 'EvidentialRegressionLoss' from 'mlguess.keras.losses' (/home/runner/work/miles-guess/miles-guess/mlguess/keras/losses.py)
```

**Comment by djgagne** [comment]
@charlie-becker it looks like you need to update your tests to use the new losses and remove or refactor the imports for the old losses.

**Comment by charlie-becker** [comment]
Model classes have been fully refactored. I have removed the tests for the non-evidential models (as they have been moved to the deprecated module). 

`.predict()` functions in both of the new model classes (classification and regression) now include a `return_uncertainties=` argument (bool).

This should thoroughly documented in the README which I can accomplish in another PR.

**Review by djgagne — APPROVED** [review]
Looks good to me. Merging.

**Pull request merged**
